version: "3.7"
services:
    pokemon:
        build: .
        ports:
        - 8000:8000
        healthcheck:
            test: ["CMD-SHELL", "curl localhost:8000/health_check/"]
            interval: 10s
            timeout: 5s
            retries: 5
        network_mode: "host"
